<?php
	global $colors;
	
	$colors = array(
		array('color' => 'White',			'hex' => '#FFFFFF'),
		array('color' => 'Ivory Cream',		'hex' => '#FFF8AF'),
		array('color' => 'Yellow',			'hex' => '#FFF212'),
		array('color' => 'Mango Orange',	'hex' => '#FDB92E'),
		array('color' => 'Bright Orange',	'hex' => '#F58634'),
		array('color' => 'Postbox Red',		'hex' => '#EF4737'),
		array('color' => 'Dark Red',		'hex' => '#E13236'),
		array('color' => 'Rustic Red',		'hex' => '#910D18'),
		array('color' => 'Plum Burgundy',	'hex' => '#891C2E'),
		array('color' => 'Aubergine',		'hex' => '#5D455C'),
		array('color' => 'Magenta',			'hex' => '#EC268F'),
		array('color' => 'Soft Pink',		'hex' => '#FF8BB5'),
		array('color' => 'Coral Pink',		'hex' => '#FF6257'),
		array('color' => 'Light Pink',		'hex' => '#FCDEE0'),
		array('color' => 'Lilac',			'hex' => '#ECB5DD'),
		array('color' => 'Lavender Purple',	'hex' => '#976298'),
		array('color' => 'Violet Purple',	'hex' => '#724178'),
		array('color' => 'Baby Blue',		'hex' => '#8FD7FF'),
		array('color' => 'Sky Blue',		'hex' => '#00AFEF'),
		array('color' => 'Azure Blue',		'hex' => '#074294'),
		array('color' => 'Brilliant Blue',	'hex' => '#3E3699'),
		array('color' => 'Navy Blue',		'hex' => '#122B5C'),
		array('color' => 'Turquoise Green', 'hex' => '#048A78'),
		array('color' => 'Mint',			'hex' => '#90E8B2'),
		array('color' => 'Lime Green',		'hex' => '#7CB228'),
		array('color' => 'Bright Green',	'hex' => '#0AAD4F'),
		array('color' => 'Green',			'hex' => '#038A4B'),
		array('color' => 'Dark Green',		'hex' => '#023D27'),
		array('color' => 'Sage',			'hex' => '#92996D'),
		array('color' => 'Taupe',			'hex' => '#BE9D72'),
		array('color' => 'Beige',			'hex' => '#F0E0AA'),
		array('color' => 'Nut Brown',		'hex' => '#CE7318'),
		array('color' => 'Choc Brown',		'hex' => '#4D2501'),
		array('color' => 'Light Grey',		'hex' => '#E6E6E6'),
		array('color' => 'Medium Grey',		'hex' => '#8C948A'),
		array('color' => 'Charcoal',		'hex' => '#545353'),
		array('color' => 'Black',			'hex' => '#000000'),
		array('color' => 'Gold',			'hex' => '#EFBB4D'),
		array('color' => 'Silver',			'hex' => '#BDBFC2')
	);
